fecha = new Date();
document.write('Año: '+fecha.getYear());
document.write('<br>');
document.write('Mes: '+fecha.getMonth());
document.write('<br>');
document.write('Día: '+fecha.getDay());
document.write('<br>');
document.write('Hora: '+fecha.getHours());
document.write('<br>');
document.write('Minutos: '+fecha.getMinutes());
document.write('<br>');
document.write('Segundos: '+fecha.getSeconds());